import { describe, expect, it } from 'vitest';
import { isaAtAltitude } from '../atmosphere';
import { USSA_1976_DATA } from '../../data/atmosphere/ussa-1976.v1';

// Independently transcribed geometric-altitude rows, US Standard Atmosphere 1976:
// Table I printed pp.53/55/59/61/63; Table III pp.100/103/107/109/111.
// Bounds are one last printed unit, including the table's limited precision;
// they are not reference outputs generated by the runtime equations.
const rows = [
  { z: 0, temp: 288.150, pressure: 1013.25, density: 1.2250, densityUnit: 0.0001, sound: 340.29, viscosity: 1.7894e-5 },
  { z: 5000, temp: 255.676, pressure: 540.48, density: 0.73643, densityUnit: 0.00001, sound: 320.55, viscosity: 1.6282e-5 },
  { z: 11000, temp: 216.774, pressure: 226.99, density: 0.36480, densityUnit: 0.00001, sound: 295.15, viscosity: 1.4223e-5 },
  { z: 20000, temp: 216.650, pressure: 55.293, density: 0.088910, densityUnit: 0.000001, sound: 295.07, viscosity: 1.4216e-5 },
  { z: 30000, temp: 226.509, pressure: 11.970, density: 0.018410, densityUnit: 0.000001, sound: 301.71, viscosity: 1.4753e-5 },
];

describe('independent USSA 1976 dry-air table holdouts', () => {
  it.each(rows)('matches the published geometric-altitude row at $z meters', (row) => {
    const actual = isaAtAltitude(row.z / 0.3048);
    expect(Math.abs(actual.tempK - row.temp), 'temperature K').toBeLessThanOrEqual(0.001);
    expect(Math.abs(actual.pressureHpa - row.pressure), 'pressure hPa').toBeLessThanOrEqual(row.z >= 20000 ? 0.001 : 0.01);
    expect(Math.abs(actual.density - row.density), 'density kg/m³').toBeLessThanOrEqual(row.densityUnit);
    expect(Math.abs(actual.speedOfSound - row.sound), 'sound speed m/s').toBeLessThanOrEqual(0.01);
    expect(Math.abs(actual.viscosity - row.viscosity), 'dynamic viscosity Pa·s').toBeLessThanOrEqual(1e-9);
  });

  it.each([11000, 20000])('remains continuous at the %s-meter geopotential layer boundary', (h) => {
    const radius = USSA_1976_DATA.constants.geopotentialEarthRadiusM;
    const z = radius * h / (radius - h);
    const below = isaAtAltitude((z - 0.001) / 0.3048);
    const above = isaAtAltitude((z + 0.001) / 0.3048);
    for (const key of ['tempK', 'pressurePa', 'density', 'speedOfSound', 'viscosity'] as const) {
      expect(Math.abs(above[key] - below[key]) / below[key], key).toBeLessThan(1e-6);
    }
    expect(above.pressurePa).toBeLessThan(below.pressurePa);
  });

  it('is finite with decreasing pressure throughout the packet altitude domain', () => {
    const radius = USSA_1976_DATA.constants.geopotentialEarthRadiusM;
    const maxH = USSA_1976_DATA.applicability.maxGeopotentialAltitudeM;
    const maxZ = radius * maxH / (radius - maxH);
    let previousPressure = Infinity;
    for (let i = 0; i <= 100; i += 1) {
      const z = -1000 + (maxZ + 1000) * i / 100;
      const actual = isaAtAltitude(z / 0.3048);
      for (const key of ['tempK', 'pressurePa', 'density', 'speedOfSound', 'viscosity'] as const) {
        expect(Number.isFinite(actual[key]) && actual[key] > 0, key).toBe(true);
      }
      expect(actual.pressurePa).toBeLessThan(previousPressure); previousPressure = actual.pressurePa;
    }
  });
});
